# Generated by Django 2.2.4 on 2019-08-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storageTime', models.DateTimeField(verbose_name='入库时间')),
                ('productSKU', models.CharField(max_length=80, verbose_name='产品SKU')),
                ('productName', models.CharField(max_length=120, verbose_name='产品名称')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=100000, verbose_name='成本价')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=100000, verbose_name='产品重量')),
                ('storageQuantity', models.DecimalField(decimal_places=2, default=0, max_digits=100000, verbose_name='入库数量')),
                ('selloutQuantity', models.DecimalField(decimal_places=2, default=0, max_digits=100000, verbose_name='出库重量')),
                ('remainQuantity', models.DecimalField(decimal_places=2, default=0, max_digits=100000, verbose_name='仓库余量')),
                ('onlineStatus', models.BooleanField(default=True, verbose_name='是否上架')),
            ],
        ),
    ]
