# Generated by Django 2.2.4 on 2019-08-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='storageTime',
            field=models.DateTimeField(auto_now=True, verbose_name='入库时间'),
        ),
    ]
