# Generated by Django 2.2.4 on 2019-08-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190807_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storageTime', models.DateTimeField(auto_now=True, verbose_name='入库时间')),
                ('productSKU', models.CharField(max_length=80, verbose_name='产品SKU')),
                ('productName', models.CharField(max_length=120, verbose_name='产品名称')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=100000, verbose_name='成本价')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=100000, verbose_name='产品重量')),
                ('storageQuantity', models.DecimalField(decimal_places=2, default=0, max_digits=100000, verbose_name='入库数量')),
                ('onlineStatus', models.BooleanField(default=True, verbose_name='是否上架')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOutStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storageTime', models.DateTimeField(auto_now=True, verbose_name='出库时间')),
                ('productSKU', models.CharField(max_length=80, verbose_name='产品SKU')),
                ('productName', models.CharField(max_length=120, verbose_name='产品名称')),
                ('storageQuantity', models.DecimalField(decimal_places=2, default=0, max_digits=100000, verbose_name='出库数量')),
                ('remainQuantity', models.DecimalField(decimal_places=2, default=0, max_digits=100000, verbose_name='库存余量')),
                ('onlineStatus', models.BooleanField(default=True, verbose_name='是否上架')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
