# Generated by Django 2.2.4 on 2019-08-08 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190808_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinstorage',
            options={'verbose_name': '产品入库', 'verbose_name_plural': '产品入库'},
        ),
        migrations.AlterModelOptions(
            name='productoutstorage',
            options={'verbose_name': '产品出库', 'verbose_name_plural': '产品出库'},
        ),
    ]
